<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SHOPPING CART TESTS"
           tests="4"
           failures="1"
           errors="0"
           skipped="0"
           time="36.412">
  <properties />
            <testcase name="t4_CheckoutItem_With_VAT" time="2.440" classname="ShoppingTests.TESTS_ShoppingCartRegisterAccount">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	expected [2] but found [120]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [2] but found [120]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
  Pages.SHOPPING_CART_PAGE.assertEcoTaxValue(SHOPPING_CART_PAGE.java:290)
  ShoppingTests.TESTS_ShoppingCartRegisterAccount.t4_CheckoutItem_With_VAT(TESTS_ShoppingCartRegisterAccount.java:226)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  java.base/java.lang.reflect.Method.invoke(Method.java:578)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:794)
  org.testng.TestRunner.run(TestRunner.java:596)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
  org.testng.SuiteRunner.run(SuiteRunner.java:276)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
  org.testng.TestNG.runSuites(TestNG.java:1063)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="t2_shopingCart_AddMultipleItemsVerification" time="4.310" classname="ShoppingTests.TESTS_ShoppingCartRegisterAccount" />
                <testcase name="t1_shoppingCartVerificationAndRemoveProducts" time="6.323" classname="ShoppingTests.TESTS_ShoppingCartRegisterAccount" />
                <testcase name="t3_CheckoutItem_Without_VAT" time="23.339" classname="ShoppingTests.TESTS_ShoppingCartRegisterAccount" />
      
</testsuite>
